title: <p style="color:rgb(255, 123, 0); font-size:25px"> Minhyang Mia Suh, Ph.D.  </p>  # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  UX & HCI Researcher | Social Scientist 
  <br>Currently @ Google<br><br>
  <a style="color:rgb(255, 123, 0);href="https://www.linkedin.com/in/miasuh/"> LinkedIn </a> | <a href="https://www.miasuh.info/"> MyCV </a> </p>

theme: jekyll-theme-minimal
