title: <p style="color:rgb(255, 123, 0)"> Minhyang Mia Suh,</p> <p style="font-size=10px; color:rgb(255, 123, 0)") Ph.D.  </p>  # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  UX & HCI Researcher | Social Scientist 
  <br>Currently @ Google<br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
